# Generated by Django 2.2.1 on 2019-05-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publication_year', models.IntegerField()),
                ('state', models.IntegerField(choices=[(0, 'Available'), (1, 'Sold')])),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('du_date', models.DateField(null=True)),
                ('book', models.ManyToManyField(related_name='books', to='manager.Book')),
            ],
        ),
    ]
