# Generated by Django 2.2.1 on 2019-05-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='du_date',
        ),
    ]
